// Every `#[tauri::command]` exposed by the plugin must be listed here so the
// permission files are generated. Grows phase by phase (sessions, snippets,
// forwards come online in later milestones).
const COMMANDS: &[&str] = &[
    "list_hosts",
    "create_host",
    "update_host",
    "delete_host",
    "list_groups",
    "create_group",
    "delete_group",
    "open_session",
    "send_input",
    "resize_session",
    "close_session",
    "list_snippets",
    "create_snippet",
    "update_snippet",
    "delete_snippet",
    "list_forwards",
    "create_forward",
    "delete_forward",
    "start_forward",
    "stop_forward",
    "sftp_open",
    "sftp_list",
    "sftp_download",
    "sftp_upload",
    "sftp_mkdir",
    "sftp_remove",
    "sftp_rename",
    "sftp_close",
    "list_known_hosts",
    "remove_known_host",
    "respond_host_key",
    "sftp_read_text",
    "sftp_upload_dir",
    "sftp_download_dir",
    "local_home",
    "local_roots",
    "local_list",
    "local_read_text",
    "local_remove",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();
}
